// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPoH3MAVrpxfbo1UDDcraweyXfbnkVNU',
    appId: '1:1044635324108:web:19785b750f471fe0c5fc69',
    messagingSenderId: '1044635324108',
    projectId: 'reef-controller',
    authDomain: 'reef-controller.firebaseapp.com',
    databaseURL: 'https://reef-controller-default-rtdb.firebaseio.com',
    storageBucket: 'reef-controller.firebasestorage.app',
    measurementId: 'G-Y6R3SJ2XJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZB8PW3yH2R4M27Ia22T09h_FEARVYBg8',
    appId: '1:1044635324108:android:ae46f5ab75bca88ac5fc69',
    messagingSenderId: '1044635324108',
    projectId: 'reef-controller',
    databaseURL: 'https://reef-controller-default-rtdb.firebaseio.com',
    storageBucket: 'reef-controller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgz0H4X3DRKebPYlFj73VRisB7sPv9wA',
    appId: '1:1044635324108:ios:06a26c0e810b7396c5fc69',
    messagingSenderId: '1044635324108',
    projectId: 'reef-controller',
    databaseURL: 'https://reef-controller-default-rtdb.firebaseio.com',
    storageBucket: 'reef-controller.firebasestorage.app',
    iosClientId: '1044635324108-dgjhckfh3ohr4chitta8qt5tvu7edkbf.apps.googleusercontent.com',
    iosBundleId: 'com.mikeyt1.reeflynk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgz0H4X3DRKebPYlFj73VRisB7sPv9wA',
    appId: '1:1044635324108:ios:3980747f57c5d8f5c5fc69',
    messagingSenderId: '1044635324108',
    projectId: 'reef-controller',
    databaseURL: 'https://reef-controller-default-rtdb.firebaseio.com',
    storageBucket: 'reef-controller.firebasestorage.app',
    iosBundleId: 'com.example.reeflynk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPoH3MAVrpxfbo1UDDcraweyXfbnkVNU',
    appId: '1:1044635324108:web:f2879ef73a0ac178c5fc69',
    messagingSenderId: '1044635324108',
    projectId: 'reef-controller',
    authDomain: 'reef-controller.firebaseapp.com',
    databaseURL: 'https://reef-controller-default-rtdb.firebaseio.com',
    storageBucket: 'reef-controller.firebasestorage.app',
    measurementId: 'G-FM6PBDQHZM',
  );

}